import { prisma } from "../../lib/prisma.js";
import { AppError } from "../../lib/errors.js";
import { assertCommerceReferences, calculateDocument, itemCreateData, nextDocumentNumber } from "../commerce/document.service.js";
import type { LineItemInput } from "../commerce/document.schemas.js";

type CreateQuotationInput={customerId:string;currency:"USD"|"LBP";discount:number;notes?:string|null;terms?:string|null;issueDate:Date;expiryDate:Date;items:LineItemInput[]};
export async function createQuotation(businessId:string,userId:string,input:CreateQuotationInput){if(input.expiryDate<input.issueDate)throw new AppError(400,"INVALID_EXPIRY_DATE","Expiry date must be after issue date");await assertCommerceReferences(businessId,input.customerId,input.items);const totals=calculateDocument(input.items,input.discount);return prisma.$transaction(async tx=>{const quotationNumber=await nextDocumentNumber(tx,businessId,"quotation");const quotation=await tx.quotation.create({data:{businessId,customerId:input.customerId,createdById:userId,quotationNumber,issueDate:input.issueDate,expiryDate:input.expiryDate,currency:input.currency,subtotal:totals.subtotal,discount:totals.discount,tax:totals.tax,total:totals.total,notes:input.notes,terms:input.terms,items:{create:totals.items.map(item=>itemCreateData(businessId,item))}},include:{items:true,customer:true}});await tx.activity.create({data:{businessId,customerId:input.customerId,actorId:userId,type:"QUOTATION_CREATED",metadata:{quotationId:quotation.id,quotationNumber}}});return quotation;});}

export async function convertQuotation(businessId:string,userId:string,quotationId:string,target:"invoice"|"order"){
  return prisma.$transaction(async tx=>{const quotation=await tx.quotation.findFirst({where:{id:quotationId,businessId,deletedAt:null},include:{items:true,convertedInvoice:true,convertedOrder:true}});if(!quotation)throw new AppError(404,"QUOTATION_NOT_FOUND","Quotation was not found");if(quotation.convertedInvoice||quotation.convertedOrder||quotation.status==="CONVERTED")throw new AppError(409,"QUOTATION_ALREADY_CONVERTED","Quotation was already converted");
    if(target==="invoice"){const invoiceNumber=await nextDocumentNumber(tx,businessId,"invoice");const dueDate=new Date();dueDate.setDate(dueDate.getDate()+30);const invoice=await tx.invoice.create({data:{businessId,customerId:quotation.customerId,createdById:userId,sourceQuotationId:quotation.id,invoiceNumber,issueDate:new Date(),dueDate,currency:quotation.currency,subtotal:quotation.subtotal,discount:quotation.discount,tax:quotation.tax,total:quotation.total,amountDue:quotation.total,notes:quotation.notes,terms:quotation.terms,items:{create:quotation.items.map(item=>({businessId,productId:item.productId,name:item.name,description:item.description,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,taxRate:item.taxRate,lineTotal:item.lineTotal}))}}});await tx.quotation.update({where:{id:quotation.id},data:{status:"CONVERTED"}});await tx.activity.create({data:{businessId,customerId:quotation.customerId,actorId:userId,type:"INVOICE_CREATED",metadata:{invoiceId:invoice.id,sourceQuotationId:quotation.id}}});return invoice;}
    const orderNumber=await nextDocumentNumber(tx,businessId,"order");const order=await tx.order.create({data:{businessId,customerId:quotation.customerId,createdById:userId,sourceQuotationId:quotation.id,orderNumber,currency:quotation.currency,subtotal:quotation.subtotal,discount:quotation.discount,tax:quotation.tax,total:quotation.total,paymentMethod:"CASH_ON_DELIVERY",items:{create:quotation.items.map(item=>({businessId,productId:item.productId,name:item.name,description:item.description,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,taxRate:item.taxRate,lineTotal:item.lineTotal}))}}});await tx.quotation.update({where:{id:quotation.id},data:{status:"CONVERTED"}});await tx.activity.create({data:{businessId,customerId:quotation.customerId,actorId:userId,type:"ORDER_CREATED",metadata:{orderId:order.id,sourceQuotationId:quotation.id}}});return order;});
}
