import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router";
import { z } from "zod";
import { api, setAccessToken } from "../lib/api";
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(8) });
const registerSchema = loginSchema.extend({ firstName: z.string().min(1), lastName: z.string().min(1), businessName: z.string().min(2) });
type Values = z.infer<typeof registerSchema>;
export function AuthPage({ register = false }: { register?: boolean }) {
  const schema = register ? registerSchema : loginSchema; const navigate = useNavigate(); const [error, setError] = useState("");
  const { register: field, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ defaultValues: { email: "", password: "", firstName: "", lastName: "", businessName: "" } });
  const submit = async (values: Values) => { try { setError(""); const { data } = await api.post(register ? "/auth/register" : "/auth/login", schema.parse(values)); setAccessToken(data.data.accessToken); navigate(register ? "/onboarding" : "/", { replace: true }); window.location.reload(); } catch (e: unknown) { const value = e as { response?: { data?: { error?: { message?: string } } } }; setError(value.response?.data?.error?.message ?? "Something went wrong"); } };
  return <div className="grid min-h-screen lg:grid-cols-2"><section className="hidden bg-ink p-14 text-white lg:flex lg:flex-col lg:justify-between"><div className="text-2xl font-bold">scalora<span className="text-brand-500">.</span></div><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-brand-500">Built for business in Lebanon</p><h1 className="mt-5 text-5xl font-semibold leading-tight">Turn every conversation into a stronger customer relationship.</h1><p className="mt-6 text-lg leading-8 text-slate-400">Customers, sales, and follow-ups in one calm workspace.</p></div><p className="text-sm text-slate-500">Scalora CRM</p></section><section className="flex items-center justify-center p-6"><form onSubmit={handleSubmit(submit)} className="w-full max-w-md"><div className="mb-10 text-2xl font-bold lg:hidden">scalora<span className="text-brand-500">.</span></div><h2 className="text-3xl font-bold">{register ? "Create your workspace" : "Welcome back"}</h2><p className="mt-2 text-slate-500">{register ? "Start your 14-day trial." : "Sign in to continue to Scalora."}</p><div className="mt-8 space-y-4">{register && <><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">First name<input className="field mt-1.5" {...field("firstName")}/></label><label className="text-sm font-medium">Last name<input className="field mt-1.5" {...field("lastName")}/></label></div><label className="block text-sm font-medium">Business name<input className="field mt-1.5" {...field("businessName")}/></label></>}<label className="block text-sm font-medium">Email<input type="email" className="field mt-1.5" {...field("email")}/><span className="text-xs text-red-600">{errors.email?.message}</span></label><label className="block text-sm font-medium">Password<input type="password" className="field mt-1.5" {...field("password")}/><span className="text-xs text-red-600">{errors.password?.message}</span></label>{error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={isSubmitting} className="btn-primary w-full">{isSubmitting ? "Please wait…" : register ? "Create workspace" : "Sign in"}</button></div><p className="mt-6 text-center text-sm text-slate-500">{register ? "Already have an account? " : "New to Scalora? "}<Link className="font-semibold text-brand-700" to={register ? "/login" : "/register"}>{register ? "Sign in" : "Create an account"}</Link></p></form></section></div>;
}
