import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { Link } from "react-router";

const CONTACT_EMAIL = "scalora.socialmedia.agency@gmail.com";
const UPDATED = "July 15, 2026";

type LegalSection = { title: string; paragraphs?: string[]; items?: string[] };

function LegalLayout({ title, summary, children }: { title: string; summary: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-slate-50">
    <header className="border-b bg-ink text-white">
      <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5">
        <Link to="/" className="text-xl font-bold">scalora<span className="text-brand-500">.</span></Link>
        <Link to="/login" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-white"><ArrowLeft size={16}/>Back to Scalora</Link>
      </div>
    </header>
    <article className="mx-auto max-w-4xl px-6 py-12">
      <div className="rounded-3xl border bg-white p-7 shadow-card sm:p-10">
        <div className="flex items-start gap-4"><span className="rounded-2xl bg-brand-50 p-3 text-brand-700"><ShieldCheck/></span><div><p className="text-sm font-bold uppercase tracking-wide text-brand-700">Scalora CRM</p><h1 className="mt-1 text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">{summary}</p><p className="mt-2 text-sm text-slate-400">Last updated: {UPDATED}</p></div></div>
        <div className="mt-10 space-y-9 text-[15px] leading-7 text-slate-700">{children}</div>
      </div>
    </article>
    <LegalFooter/>
  </main>;
}

function Section({ title, paragraphs = [], items = [] }: LegalSection) {
  return <section><h2 className="text-xl font-bold text-slate-900">{title}</h2>{paragraphs.map((paragraph) => <p key={paragraph} className="mt-3">{paragraph}</p>)}{items.length > 0 && <ul className="mt-3 list-disc space-y-2 pl-6">{items.map((item) => <li key={item}>{item}</li>)}</ul>}</section>;
}

function ContactSection() {
  return <section className="rounded-2xl bg-brand-50 p-5"><h2 className="text-xl font-bold text-slate-900">Contact us</h2><p className="mt-2">Questions, privacy requests, or deletion requests can be sent to:</p><a className="mt-3 inline-flex items-center gap-2 font-semibold text-brand-700 underline" href={`mailto:${CONTACT_EMAIL}`}><Mail size={17}/>{CONTACT_EMAIL}</a></section>;
}

function LegalFooter() {
  return <footer className="border-t bg-white"><nav aria-label="Legal" className="mx-auto flex max-w-4xl flex-wrap gap-x-6 gap-y-2 px-6 py-6 text-sm font-medium text-slate-600"><Link className="hover:text-brand-700" to="/privacy">Privacy Policy</Link><Link className="hover:text-brand-700" to="/terms">Terms of Service</Link><Link className="hover:text-brand-700" to="/data-deletion">User Data Deletion</Link><a className="hover:text-brand-700" href={`mailto:${CONTACT_EMAIL}`}>Contact</a></nav></footer>;
}

export function PrivacyPolicyPage() {
  return <LegalLayout title="Privacy Policy" summary="This policy explains how Scalora collects, uses, shares, protects, and deletes information when businesses use our CRM and WhatsApp integration.">
    <Section title="1. Who we are and scope" paragraphs={["Scalora CRM (\"Scalora\", \"we\", \"us\", or \"our\") provides a multi-tenant customer relationship management platform for businesses. This policy applies to the Scalora website, application, APIs, and integrations, including the WhatsApp Business Platform integration.", "A business that creates a Scalora workspace generally controls the customer and communications data uploaded to that workspace. Scalora processes that data to provide the service on the business's instructions. Scalora is responsible for account, billing, security, and service-usage information that we collect for our own operations."]}/>
    <Section title="2. Information we collect" items={["Account and workspace information, including names, business names, email addresses, roles, authentication records, settings, and team invitations.", "CRM and commerce information submitted by a workspace, including customer names and contact details, tags, notes, pipeline records, follow-ups, products, orders, quotations, invoices, campaign settings, and consent records.", "WhatsApp information, including WhatsApp Business Account and phone-number identifiers, business profile details, templates, message content, attachments, delivery/read status, and conversation metadata.", "Meta integration data needed to operate the connection, including authorization codes and access tokens. Authorization codes are exchanged on the server, access tokens are encrypted at rest, and Scalora does not receive a user's Meta password.", "Technical and security data, including IP address, device/browser information, timestamps, audit events, API and error logs, session cookies, and locally stored authentication state.", "Support communications and other information a person chooses to send to us."]}/>
    <Section title="3. How we use information" items={["Provide, secure, maintain, troubleshoot, and improve Scalora and its integrations.", "Authenticate users, enforce workspace roles, prevent cross-tenant access, and maintain audit trails.", "Send and receive WhatsApp messages at the direction of a workspace, synchronize templates and delivery status, and process webhooks from Meta.", "Manage customers, sales workflows, documents, reporting, notifications, and team collaboration.", "Respond to support, privacy, security, and legal requests.", "Detect fraud, abuse, unauthorized access, and violations of our Terms.", "Comply with applicable law and enforce agreements."]}/>
    <Section title="4. Legal grounds and business responsibilities" paragraphs={["Depending on the context and applicable law, processing is based on performance of a contract, legitimate interests in operating and securing the service, consent, or compliance with legal obligations. Workspace owners are responsible for having a valid legal basis to add contacts, retain their data, and communicate with them.", "Businesses using WhatsApp through Scalora must obtain and record any consent required for messaging, honor opt-outs, and follow the WhatsApp Business Messaging Policy and applicable anti-spam, consumer-protection, and privacy laws."]}/>
    <Section title="5. How information is shared" items={["With authorized members of the relevant Scalora workspace, according to their assigned roles.", "With Meta and WhatsApp when a workspace connects WhatsApp or directs Scalora to transmit messages, templates, media, or related requests.", "With infrastructure and service providers that host, store, secure, monitor, or support Scalora, subject to appropriate contractual and security safeguards.", "With professional advisers, authorities, or other parties when reasonably necessary to comply with law, protect rights and safety, investigate abuse, or establish legal claims.", "As part of a merger, financing, acquisition, restructuring, or sale of assets, subject to appropriate confidentiality and notice requirements."]}/>
    <Section title="6. International processing" paragraphs={["Scalora, Meta, and service providers may process information in countries other than the user's country. Where required, we use appropriate contractual or legal safeguards for international transfers. A workspace owner is responsible for any additional transfer requirements that apply to the data it controls."]}/>
    <Section title="7. Retention and deletion" paragraphs={["We retain information while a workspace account is active and as needed to provide the service, meet legal obligations, resolve disputes, prevent abuse, and enforce agreements. Retention periods vary by data type, workspace instructions, legal requirements, and backup schedules.", "After a verified deletion request, we delete or de-identify information that we are not legally required to retain. We aim to complete active-system deletion within 30 days. Residual encrypted backups may persist for up to 90 days before scheduled expiration, unless a longer period is legally required. We may retain limited security, audit, transaction, or legal records where necessary."]}/>
    <Section title="8. Security" paragraphs={["We use measures designed to protect information, including tenant-scoped authorization, encryption of sensitive integration credentials, encrypted network transport, access controls, validation, audit logging, and restricted production access. No system is completely secure, and users must protect their passwords, devices, and workspace access."]}/>
    <Section title="9. Your choices and rights" paragraphs={["Depending on applicable law, a person may have rights to access, correct, export, restrict, object to, or delete personal information. Workspace contacts should normally contact the business that controls their data first. Requests may also be sent to Scalora using the contact below. We may verify identity and workspace authority before acting.", "Users can disconnect WhatsApp from Scalora's WhatsApp settings. Disconnecting revokes Scalora's stored connection but does not automatically delete information held independently by Meta, WhatsApp, or the connected business."]}/>
    <Section title="10. Children" paragraphs={["Scalora is a business service and is not directed to children. Users must be at least 18 years old or the legal age required to enter a binding business agreement in their jurisdiction."]}/>
    <Section title="11. Changes to this policy" paragraphs={["We may update this policy to reflect changes to Scalora, our providers, or legal requirements. We will post the updated policy here and change the last-updated date. Material changes may also be communicated through the service or by email."]}/>
    <ContactSection/>
  </LegalLayout>;
}

export function TermsOfServicePage() {
  return <LegalLayout title="Terms of Service" summary="These terms govern access to and use of Scalora CRM, including its WhatsApp Business Platform integration.">
    <Section title="1. Acceptance and eligibility" paragraphs={["By creating an account, accepting an invitation, or using Scalora, you agree to these Terms and our Privacy Policy. If you use Scalora for an organization, you represent that you have authority to bind that organization. You must be at least 18 years old and legally able to enter this agreement."]}/>
    <Section title="2. The service" paragraphs={["Scalora provides CRM, customer communications, sales workflow, reporting, commerce-document, team, and integration features. We may improve, add, modify, or discontinue features. Availability of third-party integrations depends on their providers and may change outside our control."]}/>
    <Section title="3. Accounts and workspace administration" items={["Provide accurate registration and business information and keep it current.", "Protect credentials, use appropriate access roles, and notify us promptly of suspected unauthorized access.", "Workspace owners control membership, connected accounts, settings, and workspace data and are responsible for actions taken by invited users.", "Do not share accounts or attempt to access another business's workspace or data."]}/>
    <Section title="4. Customer data and privacy" paragraphs={["You retain ownership of information and content submitted to your workspace. You grant Scalora the limited rights needed to host, process, transmit, back up, and display that content to provide and secure the service.", "You are responsible for the accuracy and legality of your content, providing required privacy notices, responding to data-subject requests, and obtaining any consent or authorization required to collect, upload, use, or communicate with contacts."]}/>
    <Section title="5. WhatsApp and Meta requirements" items={["Your use of WhatsApp through Scalora is also governed by Meta's and WhatsApp's applicable terms, policies, commerce rules, template rules, and messaging policies.", "You must obtain valid recipient opt-in where required, identify your business, honor opt-outs promptly, and avoid deceptive, unlawful, abusive, or unsolicited messaging.", "You are responsible for templates, campaigns, recipients, products, and message content submitted through your workspace.", "Meta may review or reject templates, restrict numbers, change API behavior, impose messaging limits, or suspend accounts. Scalora does not control those decisions.", "You may not provide Scalora with another party's Meta or WhatsApp assets without authorization."]}/>
    <Section title="6. Acceptable use" items={["Do not use Scalora for spam, harassment, fraud, impersonation, malware, exploitation, illegal sales, or infringement of another person's rights.", "Do not probe, scan, disrupt, overload, reverse engineer, bypass security, scrape, or access the service through unauthorized automated means.", "Do not upload secrets or sensitive personal information unless necessary, lawful, and appropriately protected.", "Do not use the service in a way that violates law, these Terms, a third-party platform policy, or another person's privacy or intellectual-property rights."]}/>
    <Section title="7. Plans, fees, and taxes" paragraphs={["Features and usage limits may depend on the selected plan. If paid services are enabled, prices, billing periods, renewal terms, and applicable limits will be presented before purchase. Customers are responsible for applicable taxes and separate third-party charges, including Meta or WhatsApp messaging charges, unless expressly stated otherwise."]}/>
    <Section title="8. Intellectual property and feedback" paragraphs={["Scalora and its software, design, documentation, trademarks, and related materials are owned by Scalora or its licensors. Except for the limited right to use the service under these Terms, no rights are transferred. If you provide feedback, you permit us to use it without restriction or compensation, without identifying you publicly."]}/>
    <Section title="9. Suspension and termination" paragraphs={["You may stop using Scalora at any time and may request workspace deletion. We may suspend or terminate access when reasonably necessary to address security risk, unlawful conduct, non-payment, material breach, third-party platform restrictions, or harm to Scalora or others. Where practical, we will provide notice and an opportunity to remedy the issue."]}/>
    <Section title="10. Third-party services" paragraphs={["Scalora may interoperate with Meta, WhatsApp, hosting, storage, and other third-party services. Their terms and privacy practices apply independently. We are not responsible for third-party downtime, policy decisions, account restrictions, content, or changes to their services."]}/>
    <Section title="11. Disclaimers and liability" paragraphs={["To the extent permitted by law, Scalora is provided on an \"as is\" and \"as available\" basis. We do not guarantee uninterrupted operation, message delivery, template approval, sales outcomes, or preservation of data outside our reasonable control.", "To the maximum extent permitted by law, Scalora will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost profits, lost opportunities, or loss caused by third-party platforms. Any limitation that cannot legally apply will be limited to the greatest extent permitted by law."]}/>
    <Section title="12. Governing law and changes" paragraphs={["These Terms are governed by the laws of Lebanon, without regard to conflict-of-law rules, unless mandatory consumer or data-protection law requires otherwise. We may update these Terms and will post the revised version with a new last-updated date. Continued use after an update takes effect constitutes acceptance where permitted by law."]}/>
    <ContactSection/>
  </LegalLayout>;
}

export function DataDeletionPage() {
  return <LegalLayout title="User Data Deletion Instructions" summary="Scalora users and people whose information is stored by a Scalora business can request access, correction, or deletion using the instructions below.">
    <Section title="Delete or disconnect WhatsApp access" items={["Sign in to Scalora as the workspace owner.", "Open Settings, then WhatsApp Cloud API.", "Select the disconnect button and confirm. Scalora will disable the connection and replace the stored WhatsApp access and verification credentials.", "You may also remove Scalora's access from your Meta Business settings. Information held independently by Meta or WhatsApp must be managed through those services."]}/>
    <Section title="Request deletion of a Scalora account or workspace" paragraphs={["Send an email from the address associated with your Scalora account to the address below with the subject \"Scalora data deletion request\"."]} items={["Include your full name and Scalora login email.", "Identify the workspace or business name.", "State whether you want your user profile, a connected Meta/WhatsApp account, specific customer information, or the entire workspace deleted.", "For a Meta/WhatsApp request, include the business display name and connected phone number. Do not send passwords, access tokens, verification codes, or payment details.", "If you are a customer contact rather than a Scalora user, identify the business that contacted you and the phone number or email associated with your record."]}/>
    <Section title="Verification and completion" paragraphs={["We will acknowledge the request and may ask for information needed to verify identity, workspace ownership, or authority. This protects data from unauthorized deletion.", "After verification, we aim to delete or de-identify eligible information from active systems within 30 days and confirm completion by email. Encrypted backups may remain until scheduled expiration for up to 90 days. Limited records may be retained where required for security, fraud prevention, legal compliance, dispute resolution, or financial recordkeeping."]}/>
    <Section title="What deletion covers" items={["Scalora user profile and authentication records that are not required for security or legal purposes.", "Workspace configuration, team records, CRM contacts, conversations, messages, templates, campaigns, files, reports, and commerce records selected for deletion, subject to legal retention duties.", "Encrypted Meta and WhatsApp access credentials and connection identifiers held by Scalora.", "Operational records that can reasonably be deleted or de-identified without compromising security and legal obligations."]}/>
    <Section title="Important limitations" paragraphs={["Deleting data from Scalora does not delete copies controlled independently by another workspace member, the business that originally collected the information, message recipients, Meta, WhatsApp, or another third party. Contact those parties separately where necessary."]}/>
    <ContactSection/>
  </LegalLayout>;
}
