import { PrismaClient, type MembershipRole } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();
const firstNames=["Maya","Karim","Nour","Rami","Lea","Jad","Sara","Tarek","Dana","Ziad","Rita","Fadi","Lynn","Omar","Mira"];
const lastNames=["Haddad","Khoury","Saad","Nassar","Saliba","Mansour","Farah","Azar","Karam","Habib"];
async function main(){
  const passwordHash=await bcrypt.hash("Demo123!",12);
  const business=await prisma.business.upsert({where:{slug:"scalora-demo"},update:{},create:{name:"Cedar & Co.",slug:"scalora-demo",category:"CLOTHING",country:"LB",currency:"USD",timezone:"Asia/Beirut",phone:"+9611123456",employeeRange:"6-15",mainObjective:"Grow repeat sales",onboardingComplete:true}});
  const people=[{email:"owner@demo.scalora.app",firstName:"Chris",lastName:"Owner",role:"OWNER"},{email:"admin@demo.scalora.app",firstName:"Maya",lastName:"Admin",role:"ADMIN"},{email:"agent@demo.scalora.app",firstName:"Karim",lastName:"Sales",role:"SALES_AGENT"}] as const;
  const users=[]; for(const person of people){const user=await prisma.user.upsert({where:{email:person.email},update:{passwordHash},create:{email:person.email,passwordHash,firstName:person.firstName,lastName:person.lastName}});await prisma.businessMember.upsert({where:{businessId_userId:{businessId:business.id,userId:user.id}},update:{role:person.role as MembershipRole,status:"ACTIVE"},create:{businessId:business.id,userId:user.id,role:person.role as MembershipRole}});users.push(user);}
  await prisma.subscription.upsert({where:{businessId:business.id},update:{},create:{businessId:business.id,trialEnd:new Date(Date.now()+14*86_400_000)}});
  const tagData=[{name:"VIP",color:"#7c3aed"},{name:"Follow up",color:"#f59e0b"},{name:"Returning customer",color:"#16a34a"},{name:"Payment pending",color:"#dc2626"}];
  for(const tag of tagData)await prisma.tag.upsert({where:{businessId_name:{businessId:business.id,name:tag.name}},update:{color:tag.color},create:{...tag,businessId:business.id}});
  let pipeline=await prisma.pipeline.findFirst({where:{businessId:business.id,isDefault:true}}); if(!pipeline)pipeline=await prisma.pipeline.create({data:{businessId:business.id,name:"Default sales pipeline",isDefault:true}});
  const stages=[{name:"New lead",probability:10,color:"#64748b"},{name:"Contacted",probability:25,color:"#3b82f6"},{name:"Qualified",probability:45,color:"#8b5cf6"},{name:"Proposal sent",probability:65,color:"#f59e0b"},{name:"Negotiation",probability:80,color:"#f97316"},{name:"Won",probability:100,color:"#16a34a",isWon:true},{name:"Lost",probability:0,color:"#dc2626",isLost:true}];
  const stageRows=[]; for(let i=0;i<stages.length;i++){const stage=stages[i]!;stageRows.push(await prisma.pipelineStage.upsert({where:{pipelineId_position:{pipelineId:pipeline.id,position:i}},update:stage,create:{...stage,position:i,pipelineId:pipeline.id,businessId:business.id}}));}
  if(await prisma.customer.count({where:{businessId:business.id}})===0){for(let i=0;i<30;i++){const customer=await prisma.customer.create({data:{businessId:business.id,firstName:firstNames[i%firstNames.length]!,lastName:lastNames[i%lastNames.length]!,phone:`+9613${String(100000+i).padStart(6,"0")}`,normalizedPhone:`+9613${String(100000+i).padStart(6,"0")}`,email:`customer${i+1}@example.com`,normalizedEmail:`customer${i+1}@example.com`,city:i%2?"Beirut":"Jounieh",source:i%3===0?"WHATSAPP":i%3===1?"INSTAGRAM":"REFERRAL",lifecycleStage:i%7===5?"WON":"NEW_LEAD",assignedUserId:users[2]!.id,marketingOptIn:i%4!==0}});const stage=stageRows[i%stageRows.length]!;await prisma.lead.create({data:{businessId:business.id,pipelineId:pipeline.id,stageId:stage.id,customerId:customer.id,assignedUserId:users[2]!.id,title:`${customer.firstName} retail opportunity`,estimatedValue:100+(i*35),probability:stage.probability,source:customer.source}});if(i<8)await prisma.followUp.create({data:{businessId:business.id,customerId:customer.id,assignedUserId:users[2]!.id,createdById:users[0]!.id,title:i%2?"Send product options":"Check purchase decision",dueAt:new Date(Date.now()+(i-2)*86_400_000),priority:i<2?"HIGH":"MEDIUM"}});await prisma.activity.create({data:{businessId:business.id,customerId:customer.id,actorId:users[0]!.id,type:"CUSTOMER_CREATED"}});}}
  console.log("Seed complete. Demo login: owner@demo.scalora.app / Demo123!");
}
main().catch((error)=>{console.error(error);process.exit(1);}).finally(()=>prisma.$disconnect());
