import { PrismaClient, type MembershipRole } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();
const firstNames=["Maya","Karim","Nour","Rami","Lea","Jad","Sara","Tarek","Dana","Ziad","Rita","Fadi","Lynn","Omar","Mira"];
const lastNames=["Haddad","Khoury","Saad","Nassar","Saliba","Mansour","Farah","Azar","Karam","Habib"];
async function main(){
  const passwordHash=await bcrypt.hash("Demo123!",12);
  const business=await prisma.business.upsert({where:{slug:"scalora-demo"},update:{address:"Hamra, Beirut",email:"hello@cedar-demo.example",website:"https://cedar-demo.example",taxNumber:"LB-DEMO-1001"},create:{name:"Cedar & Co.",slug:"scalora-demo",category:"CLOTHING",country:"LB",currency:"USD",timezone:"Asia/Beirut",phone:"+9611123456",address:"Hamra, Beirut",email:"hello@cedar-demo.example",website:"https://cedar-demo.example",taxNumber:"LB-DEMO-1001",employeeRange:"6-15",mainObjective:"Grow repeat sales",onboardingComplete:true}});
  const people=[{email:"owner@demo.scalora.app",firstName:"Chris",lastName:"Owner",role:"OWNER"},{email:"admin@demo.scalora.app",firstName:"Maya",lastName:"Admin",role:"ADMIN"},{email:"agent@demo.scalora.app",firstName:"Karim",lastName:"Sales",role:"SALES_AGENT"}] as const;
  const users=[]; for(const person of people){const user=await prisma.user.upsert({where:{email:person.email},update:{passwordHash},create:{email:person.email,passwordHash,firstName:person.firstName,lastName:person.lastName}});await prisma.businessMember.upsert({where:{businessId_userId:{businessId:business.id,userId:user.id}},update:{role:person.role as MembershipRole,status:"ACTIVE"},create:{businessId:business.id,userId:user.id,role:person.role as MembershipRole}});users.push(user);}
  await prisma.subscription.upsert({where:{businessId:business.id},update:{},create:{businessId:business.id,trialEnd:new Date(Date.now()+14*86_400_000)}});
  const tagData=[{name:"VIP",color:"#7c3aed"},{name:"Follow up",color:"#f59e0b"},{name:"Returning customer",color:"#16a34a"},{name:"Payment pending",color:"#dc2626"}];
  for(const tag of tagData)await prisma.tag.upsert({where:{businessId_name:{businessId:business.id,name:tag.name}},update:{color:tag.color},create:{...tag,businessId:business.id}});
  let pipeline=await prisma.pipeline.findFirst({where:{businessId:business.id,isDefault:true}}); if(!pipeline)pipeline=await prisma.pipeline.create({data:{businessId:business.id,name:"Default sales pipeline",isDefault:true}});
  const stages=[{name:"New lead",probability:10,color:"#64748b"},{name:"Contacted",probability:25,color:"#3b82f6"},{name:"Qualified",probability:45,color:"#8b5cf6"},{name:"Proposal sent",probability:65,color:"#f59e0b"},{name:"Negotiation",probability:80,color:"#f97316"},{name:"Won",probability:100,color:"#16a34a",isWon:true},{name:"Lost",probability:0,color:"#dc2626",isLost:true}];
  const stageRows=[]; for(let i=0;i<stages.length;i++){const stage=stages[i]!;stageRows.push(await prisma.pipelineStage.upsert({where:{pipelineId_position:{pipelineId:pipeline.id,position:i}},update:stage,create:{...stage,position:i,pipelineId:pipeline.id,businessId:business.id}}));}
  if(await prisma.customer.count({where:{businessId:business.id}})===0){for(let i=0;i<30;i++){const customer=await prisma.customer.create({data:{businessId:business.id,firstName:firstNames[i%firstNames.length]!,lastName:lastNames[i%lastNames.length]!,phone:`+9613${String(100000+i).padStart(6,"0")}`,normalizedPhone:`+9613${String(100000+i).padStart(6,"0")}`,email:`customer${i+1}@example.com`,normalizedEmail:`customer${i+1}@example.com`,city:i%2?"Beirut":"Jounieh",source:i%3===0?"WHATSAPP":i%3===1?"INSTAGRAM":"REFERRAL",lifecycleStage:i%7===5?"WON":"NEW_LEAD",assignedUserId:users[2]!.id,marketingOptIn:i%4!==0}});const stage=stageRows[i%stageRows.length]!;await prisma.lead.create({data:{businessId:business.id,pipelineId:pipeline.id,stageId:stage.id,customerId:customer.id,assignedUserId:users[2]!.id,title:`${customer.firstName} retail opportunity`,estimatedValue:100+(i*35),probability:stage.probability,source:customer.source}});if(i<8)await prisma.followUp.create({data:{businessId:business.id,customerId:customer.id,assignedUserId:users[2]!.id,createdById:users[0]!.id,title:i%2?"Send product options":"Check purchase decision",dueAt:new Date(Date.now()+(i-2)*86_400_000),priority:i<2?"HIGH":"MEDIUM"}});await prisma.activity.create({data:{businessId:business.id,customerId:customer.id,actorId:users[0]!.id,type:"CUSTOMER_CREATED"}});}}
  if(await prisma.conversation.count({where:{businessId:business.id}})===0){const customers=await prisma.customer.findMany({where:{businessId:business.id},take:12,orderBy:{createdAt:"asc"}});for(let i=0;i<customers.length;i++){const customer=customers[i]!;const conversation=await prisma.conversation.create({data:{businessId:business.id,customerId:customer.id,assignedUserId:users[2]!.id,channel:"MOCK_WHATSAPP",status:i%5===0?"PENDING":"OPEN",unreadCount:i%4,lastCustomerMessageAt:new Date(Date.now()-(i+1)*3_600_000),sessionExpiresAt:new Date(Date.now()+(23-i)*3_600_000),lastMessageAt:new Date(Date.now()-i*3_600_000),lastMessagePreview:i%2?"Can you send me the available colors?":"Thank you, I’ll confirm shortly."}});await prisma.conversationAssignment.create({data:{businessId:business.id,conversationId:conversation.id,assignedUserId:users[2]!.id,assignedById:users[0]!.id}});const messages=[{direction:"INBOUND" as const,status:"RECEIVED" as const,body:"Hello, I saw your products on Instagram.",receivedAt:new Date(Date.now()-(i+3)*3_600_000)},{direction:"OUTBOUND" as const,status:"READ" as const,body:"Welcome! How can we help you today?",senderUserId:users[2]!.id,sentAt:new Date(Date.now()-(i+2)*3_600_000),deliveredAt:new Date(Date.now()-(i+2)*3_600_000),readAt:new Date(Date.now()-(i+1)*3_600_000)},{direction:"INBOUND" as const,status:"RECEIVED" as const,body:i%2?"Can you send me the available colors?":"Thank you, I’ll confirm shortly.",receivedAt:new Date(Date.now()-i*3_600_000)}];for(const message of messages)await prisma.message.create({data:{businessId:business.id,conversationId:conversation.id,type:"TEXT",...message}});if(i<4)await prisma.internalNote.create({data:{businessId:business.id,conversationId:conversation.id,authorId:users[0]!.id,body:"High-intent customer — follow up before the weekend."}});}}
  const optedInCustomers=await prisma.customer.findMany({where:{businessId:business.id,marketingOptIn:true},orderBy:{createdAt:"asc"}});
  for(const customer of optedInCustomers){await prisma.customer.update({where:{id:customer.id},data:{marketingOptInSource:"DEMO_SEED",marketingOptInAt:customer.marketingOptInAt??customer.createdAt}});if(await prisma.consentRecord.count({where:{businessId:business.id,customerId:customer.id}})===0)await prisma.consentRecord.create({data:{businessId:business.id,customerId:customer.id,recordedById:users[0]!.id,status:"OPTED_IN",source:"DEMO_SEED",notes:"Demo consent record"}});}
  const demoAccount=await prisma.whatsAppAccount.upsert({where:{businessId:business.id},update:{},create:{businessId:business.id,whatsAppBusinessAccountId:"demo-waba",phoneNumberId:"demo-phone-number",displayPhoneNumber:"+961 1 000 000",verifiedName:"Cedar & Co. Demo",encryptedAccessToken:"demo-only",encryptedVerifyToken:"demo-only",connectionStatus:"DISCONNECTED"}});
  const demoTemplate=await prisma.whatsAppTemplate.upsert({where:{accountId_name_language:{accountId:demoAccount.id,name:"scalora_demo_offer",language:"en_US"}},update:{},create:{businessId:business.id,accountId:demoAccount.id,metaTemplateId:"demo-template",name:"scalora_demo_offer",language:"en_US",category:"MARKETING",status:"APPROVED",body:"Hello {{1}}, discover our latest collection.",variables:["firstName"]}});
  if(await prisma.campaign.count({where:{businessId:business.id}})===0){const sent=Math.min(12,optedInCustomers.length);const campaign=await prisma.campaign.create({data:{businessId:business.id,templateId:demoTemplate.id,createdById:users[0]!.id,name:"Summer collection preview",audience:{filters:{selectedTagIds:[],excludedTagIds:[],lifecycleStages:[],sources:[],assignedUserId:null},bodyVariables:["{{firstName}}"]},status:"COMPLETED",totalRecipients:sent,sentCount:sent,deliveredCount:Math.max(0,sent-1),readCount:Math.max(0,sent-3),replyCount:Math.min(3,sent),startedAt:new Date(Date.now()-2*86_400_000),completedAt:new Date(Date.now()-2*86_400_000)}});await prisma.campaignRecipient.createMany({data:optedInCustomers.slice(0,sent).map((customer,index)=>({businessId:business.id,campaignId:campaign.id,customerId:customer.id,phone:customer.normalizedPhone!,variables:[customer.firstName],status:index<3?"REPLIED":index<sent-3?"READ":index<sent-1?"DELIVERED":"SENT",queuedAt:new Date(Date.now()-2*86_400_000),sentAt:new Date(Date.now()-2*86_400_000),deliveredAt:index<sent-1?new Date(Date.now()-2*86_400_000):null,readAt:index<sent-3?new Date(Date.now()-2*86_400_000):null,repliedAt:index<3?new Date(Date.now()-2*86_400_000):null}))});}
  const catalog=[{name:"Linen summer shirt",sku:"SHIRT-LINEN",type:"PRODUCT" as const,price:45,taxRate:11},{name:"Classic denim",sku:"DENIM-CLASSIC",type:"PRODUCT" as const,price:55,taxRate:11},{name:"Leather handbag",sku:"BAG-LEATHER",type:"PRODUCT" as const,price:90,taxRate:11},{name:"Gift wrapping",sku:"SERVICE-WRAP",type:"SERVICE" as const,price:5,taxRate:0}];const products=[];for(const item of catalog)products.push(await prisma.product.upsert({where:{businessId_sku:{businessId:business.id,sku:item.sku}},update:{name:item.name,price:item.price,taxRate:item.taxRate,isActive:true},create:{...item,businessId:business.id,currency:"USD"}}));
  const commerceCustomer=optedInCustomers[0]??await prisma.customer.findFirstOrThrow({where:{businessId:business.id}});const product=products[0]!;
  if(await prisma.quotation.count({where:{businessId:business.id}})===0)await prisma.quotation.create({data:{businessId:business.id,customerId:commerceCustomer.id,createdById:users[0]!.id,quotationNumber:"QUO-DEMO-00001",issueDate:new Date(),expiryDate:new Date(Date.now()+14*86_400_000),currency:"USD",subtotal:90,tax:9.9,total:99.9,status:"SENT",notes:"Demo retail quotation",items:{create:{businessId:business.id,productId:product.id,name:product.name,quantity:2,unitPrice:45,taxRate:11,lineTotal:99.9}}}});
  if(await prisma.invoice.count({where:{businessId:business.id}})===0){const invoice=await prisma.invoice.create({data:{businessId:business.id,customerId:commerceCustomer.id,createdById:users[0]!.id,invoiceNumber:"INV-DEMO-00001",issueDate:new Date(),dueDate:new Date(Date.now()+30*86_400_000),currency:"USD",subtotal:90,tax:9.9,total:99.9,amountPaid:40,amountDue:59.9,paymentStatus:"PARTIALLY_PAID",items:{create:{businessId:business.id,productId:product.id,name:product.name,quantity:2,unitPrice:45,taxRate:11,lineTotal:99.9}}}});await prisma.payment.create({data:{businessId:business.id,invoiceId:invoice.id,recordedById:users[0]!.id,amount:40,currency:"USD",method:"CASH",paidAt:new Date(),notes:"Demo partial payment"}});}
  if(await prisma.order.count({where:{businessId:business.id}})===0)await prisma.order.create({data:{businessId:business.id,customerId:commerceCustomer.id,createdById:users[0]!.id,assignedUserId:users[2]!.id,orderNumber:"ORD-DEMO-00001",currency:"USD",subtotal:55,tax:6.05,deliveryFee:4,total:65.05,paymentMethod:"CASH_ON_DELIVERY",status:"PREPARING",deliveryAddress:"Beirut, Lebanon",items:{create:{businessId:business.id,productId:products[1]!.id,name:products[1]!.name,quantity:1,unitPrice:55,taxRate:11,lineTotal:61.05}}}});
  await prisma.documentSequence.upsert({where:{businessId_key:{businessId:business.id,key:"quotation"}},update:{},create:{businessId:business.id,key:"quotation",value:1}});await prisma.documentSequence.upsert({where:{businessId_key:{businessId:business.id,key:"invoice"}},update:{},create:{businessId:business.id,key:"invoice",value:1}});await prisma.documentSequence.upsert({where:{businessId_key:{businessId:business.id,key:"order"}},update:{},create:{businessId:business.id,key:"order",value:1}});
  console.log("Seed complete. Demo login: owner@demo.scalora.app / Demo123!");
}
main().catch((error)=>{console.error(error);process.exit(1);}).finally(()=>prisma.$disconnect());
