import { Router } from "express";
import { authRouter } from "./modules/auth/auth.routes.js";
import { businessRouter } from "./modules/business/business.routes.js";
import { customerRouter } from "./modules/customers/customer.routes.js";
import { tagRouter } from "./modules/tags/tag.routes.js";
import { followUpRouter } from "./modules/follow-ups/follow-up.routes.js";
import { pipelineRouter } from "./modules/pipeline/pipeline.routes.js";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { conversationRouter } from "./modules/conversations/conversation.routes.js";
import { whatsAppRouter } from "./modules/whatsapp/whatsapp.routes.js";
import { campaignRouter } from "./modules/campaigns/campaign.routes.js";
import { consentRouter } from "./modules/consent/consent.routes.js";
import { productRouter } from "./modules/products/product.routes.js";
import { quotationRouter } from "./modules/quotations/quotation.routes.js";
import { invoiceRouter } from "./modules/invoices/invoice.routes.js";
import { orderRouter } from "./modules/orders/order.routes.js";
import { reportRouter } from "./modules/reports/report.routes.js";
import { notificationRouter } from "./modules/notifications/notification.routes.js";
import { subscriptionRouter } from "./modules/subscriptions/subscription.routes.js";
import { auditRouter } from "./modules/audit/audit.routes.js";

export const apiRouter = Router();
apiRouter.use("/auth", authRouter);
apiRouter.use("/business", businessRouter);
apiRouter.use("/customers", customerRouter);
apiRouter.use("/tags", tagRouter);
apiRouter.use("/follow-ups", followUpRouter);
apiRouter.use("/pipeline", pipelineRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/conversations", conversationRouter);
apiRouter.use("/whatsapp", whatsAppRouter);
apiRouter.use("/campaigns", campaignRouter);
apiRouter.use("/consent", consentRouter);
apiRouter.use("/products", productRouter);
apiRouter.use("/quotations", quotationRouter);
apiRouter.use("/invoices", invoiceRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/subscription", subscriptionRouter);
apiRouter.use("/audit-logs", auditRouter);
