import { BarChart3, CalendarCheck, ContactRound, FileText, LayoutDashboard, LogOut, Megaphone, Menu, MessageCircle, Package, Receipt, Settings2, ShoppingBag, TrendingUp, Users, X } from "lucide-react";
import { useState } from "react";
import { NavLink, Outlet } from "react-router";
import { useAuth } from "../lib/auth";
import { NotificationCenter } from "./NotificationCenter";
const links = [{ to: "/", label: "Dashboard", icon: LayoutDashboard }, { to: "/inbox", label: "Inbox", icon: MessageCircle }, { to: "/customers", label: "Customers", icon: ContactRound }, { to: "/pipeline", label: "Pipeline", icon: TrendingUp }, { to: "/follow-ups", label: "Follow-ups", icon: CalendarCheck }, { to: "/products", label: "Products", icon: Package }, { to: "/orders", label: "Orders", icon: ShoppingBag }, { to: "/quotations", label: "Quotations", icon: FileText }, { to: "/invoices", label: "Invoices", icon: Receipt }, { to: "/campaigns", label: "Campaigns", icon: Megaphone }, { to: "/reports", label: "Reports", icon: BarChart3 }, { to: "/team", label: "Team", icon: Users }, { to: "/settings", label: "Settings", icon: Settings2 }];
export function AppShell() {
  const [open, setOpen] = useState(false); const { session, logout } = useAuth();
  const visibleLinks = links.filter((link) => !(session?.role === "SALES_AGENT" && ["/reports", "/team"].includes(link.to)) && !(session?.role === "VIEWER" && link.to === "/team"));
  const sidebar = <aside className="flex h-full w-64 flex-col bg-ink px-4 py-5 text-white"><div className="flex items-center justify-between px-2"><div><div className="text-xl font-bold tracking-tight">scalora<span className="text-brand-500">.</span></div><div className="mt-0.5 text-xs text-slate-400">{session?.business.name}</div></div><button className="lg:hidden" onClick={() => setOpen(false)}><X size={20}/></button></div><nav className="mt-7 flex-1 space-y-1 overflow-y-auto">{visibleLinks.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === "/"} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive ? "bg-white/10 text-white" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon size={18}/>{label}</NavLink>)}</nav><button onClick={() => void logout()} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-400 hover:bg-white/5 hover:text-white"><LogOut size={18}/>Log out</button></aside>;
  return <div className="min-h-screen"><div className="fixed inset-y-0 left-0 hidden lg:block">{sidebar}</div>{open && <div className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={() => setOpen(false)}><div className="h-full" onClick={(e) => e.stopPropagation()}>{sidebar}</div></div>}<main className="min-h-screen lg:ml-64"><header className="flex h-16 items-center justify-between border-b bg-white px-4 sm:px-7"><button className="lg:hidden" onClick={() => setOpen(true)}><Menu/></button><div className="ml-auto flex items-center gap-3"><NotificationCenter/><div className="hidden text-right sm:block"><div className="text-sm font-semibold">{session?.user.firstName} {session?.user.lastName}</div><div className="text-xs text-slate-500">{session?.role.toLowerCase().replace("_", " ")}</div></div><div className="grid h-9 w-9 place-items-center rounded-full bg-brand-100 text-sm font-bold text-brand-700">{session?.user.firstName[0]}{session?.user.lastName[0]}</div></div></header><div className="p-4 sm:p-7"><Outlet/></div></main></div>;
}
