import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("../src/config/env.js",()=>({env:{WHATSAPP_API_VERSION:"v23.0"}}));
const {WhatsAppCloudProvider}=await import("../src/modules/whatsapp/cloud.provider.js");
describe("official WhatsApp Cloud provider",()=>{
  afterEach(()=>vi.unstubAllGlobals());
  it("sends text through the versioned Meta Graph endpoint",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({messages:[{id:"wamid.123"}]}),{status:200,headers:{"content-type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const provider=new WhatsAppCloudProvider("phone-123","secret-token");const result=await provider.send({businessId:"business-a",conversationId:"conversation-a",messageId:"message-a",recipientPhone:"+9613123456",type:"TEXT",body:"Hello"});expect(result.providerMessageId).toBe("wamid.123");expect(fetchMock).toHaveBeenCalledWith("https://graph.facebook.com/v23.0/phone-123/messages",expect.objectContaining({method:"POST"}));const request=fetchMock.mock.calls[0]![1] as RequestInit;expect(new Headers(request.headers).get("authorization")).toBe("Bearer secret-token");expect(JSON.parse(request.body as string)).toMatchObject({messaging_product:"whatsapp",to:"9613123456",type:"text"});});
  it("submits text templates to the connected WhatsApp business account",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"template-123",status:"PENDING",category:"UTILITY"}),{status:200,headers:{"content-type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const provider=new WhatsAppCloudProvider("phone-123","secret-token");const result=await provider.createTemplate("waba-123",{name:"order_ready",language:"en_US",category:"UTILITY",header:{text:"Order {{1}}",example:"ORD-1001"},body:"Hello {{1}}, your order is ready.",bodyExamples:["Maya"],footer:"Thank you",buttons:[{type:"QUICK_REPLY",text:"View order"}]});expect(result).toMatchObject({id:"template-123",status:"PENDING"});expect(fetchMock).toHaveBeenCalledWith("https://graph.facebook.com/v23.0/waba-123/message_templates",expect.objectContaining({method:"POST"}));const request=fetchMock.mock.calls[0]![1] as RequestInit;const payload=JSON.parse(request.body as string);expect(payload).toMatchObject({name:"order_ready",language:"en_US",category:"UTILITY"});expect(payload.components).toEqual(expect.arrayContaining([expect.objectContaining({type:"BODY",example:{body_text:[["Maya"]]}}),expect.objectContaining({type:"BUTTONS",buttons:[{type:"QUICK_REPLY",text:"View order"}]})]));});
  it("subscribes the Meta app to the connected WABA",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({success:true}),{status:200,headers:{"content-type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const provider=new WhatsAppCloudProvider("phone-123","secret-token");await expect(provider.subscribeWaba("waba-123")).resolves.toBe(true);expect(fetchMock).toHaveBeenCalledWith("https://graph.facebook.com/v23.0/waba-123/subscribed_apps",expect.objectContaining({method:"POST"}));});
  it("verifies that embedded-signup phone assets belong to the selected WABA",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{id:"phone-123"},{id:"phone-456"}]}),{status:200,headers:{"content-type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const provider=new WhatsAppCloudProvider("phone-123","secret-token");await expect(provider.verifyPhoneBelongsToWaba("waba-123")).resolves.toBe(true);expect(fetchMock).toHaveBeenCalledWith("https://graph.facebook.com/v23.0/waba-123/phone_numbers?fields=id&limit=100",expect.any(Object));});
});
